services:
  # a10y:
  #   image: test-local
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env.non-secret

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=env:OTEL_COLLECTOR_CONFIG", "${OTELCOL_ARGS}"]
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    environment:
      GRAFANA_USERNAME_TEMPO: ${GRAFANA_USERNAME_TEMPO}
      GRAFANA_API_KEY_TEMPO: ${GRAFANA_API_KEY_TEMPO}
      GRAFANA_USERNAME_PROM: ${GRAFANA_USERNAME_PROM}
      GRAFANA_API_KEY_PROM: ${GRAFANA_API_KEY_PROM}
      OTEL_COLLECTOR_CONFIG: |
        receivers:
          otlp:
            protocols:
              http: 
                endpoint: 0.0.0.0:4318
              grpc:
                endpoint: 0.0.0.0:4317
        processors:
          batch:
        exporters:
          debug:
          debug/prom:
            verbosity: detailed
          prometheusremotewrite:
            endpoint: "https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push"
            auth:
              authenticator: basicauth/prom
          otlp/tempo:
            endpoint: "tempo-prod-04-prod-us-east-0.grafana.net:443"
            auth:
              authenticator: basicauth/tempo
          otlp/jaeger:
            endpoint: jaeger-all-in-one:4317
            tls:
              insecure: true
        extensions:
          health_check:
          basicauth/tempo:
            client_auth:
              username: $${env:GRAFANA_USERNAME_TEMPO}
              password: $${env:GRAFANA_API_KEY_TEMPO}
          basicauth/prom:
            client_auth:
              username: $${env:GRAFANA_USERNAME_PROM}
              password: $${env:GRAFANA_API_KEY_PROM}
        service:
          extensions: [basicauth/tempo, basicauth/prom, health_check]
          pipelines:
            traces:
              receivers: [otlp]
              processors: [batch]
              exporters: [debug, otlp/jaeger, otlp/tempo]
            metrics:
              receivers: [otlp]
              processors: [batch]
              exporters: [debug, prometheusremotewrite]